modLoader = "javafml"
loaderVersion = "[${forgeMinLoaderVersion},)"
issueTrackerURL = "${modIssueTracker}"
displayURL = "${modHomepage}"
license = "${modLicense}"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
authors = "NaoCraftLab"
description = "${modDescription}"
logoFile = "assets/${modId}/icon.png"

[[dependencies.${modId}]]
modId = "forge"
mandatory = true
versionRange = "[${forgeMinVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "minecraft"
mandatory = true
versionRange = "${forgeMcVersionRange}"
ordering = "NONE"
side = "BOTH"

${forgeClothConfigSuggestion}