modLoader = "javafml"
loaderVersion = "[${neoforgeMinLoaderVersion},)"
issueTrackerURL = "${modIssueTracker}"
displayURL = "${modHomepage}"
license = "${modLicense}"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
authors = "NaoCraftLab"
description = "${modDescription}"
logoFile = "assets/${modId}/icon.png"

[[mixins]]
config = "${modId}.mixins.json"

[[dependencies.${modId}]]
modId = "neoforge"
mandatory = true
type = "required"
versionRange = "[${neoforgeMinVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "minecraft"
mandatory = true
type = "required"
versionRange = "[${neoforgeMinMinecraftVersion},)"
ordering = "NONE"
side = "BOTH"

${neoForgeClothConfigSuggestion}